<?php
require_once dirname(__FILE__).'/path/autoload.inc.php';
require_once dirname(__FILE__).'/page/autoload.inc';
require_once dirname(__FILE__).'/dbd/autoload.inc.php';
require_once dirname(__FILE__).'/api/autoload.inc.php';
require_once dirname(__FILE__).'/config/autoload.inc.php';
require_once dirname(__FILE__).'/sai/autoload.inc';
require_once dirname(__FILE__).'/files/autoload.inc.php';
require_once dirname(__FILE__).'/cron/autoload.inc.php';